FROM node:20

WORKDIR /app

RUN npm install -g pnpm

COPY ../../pnpm-lock.yaml ./pnpm-lock.yaml

COPY . .
RUN pnpm install --frozen-lockfile

# Build Next.js
RUN pnpm --filter web build

EXPOSE 3000
CMD ["pnpm", "--filter", "web", "start"]