version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: apps/api-server/Dockerfile.api
    container_name: turbo-api
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file:
      - ./apps/api-server/.env

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.web
    container_name: turbo-web
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - ./apps/web/.env.local

  postgres:
    image: postgres:15
    container_name: turbo-postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sbir
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: turbo-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  etl:
    build:
      context: ./sbir-etl
      dockerfile: Dockerfile.etl
    container_name: turbo-etl
    env_file:
      - ./sbir-etl/.env
    depends_on:
      - postgres
    command: ["poetry", "run", "flask", "load-sbir"]

volumes:
  postgres-data: