"""updated solicitation docs again

Revision ID: 1d6c08427722
Revises: f7f3458c53f9
Create Date: 2025-06-23 18:52:51.754513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '1d6c08427722'
down_revision: Union[str, Sequence[str], None] = 'f7f3458c53f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitation_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitation_id', sa.Integer(), nullable=True),
    sa.Column('chunk', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['solicitation_id'], ['solicitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitation_documents')
    # ### end Alembic commands ###
