"""create solicitation_topics table

Revision ID: 5a24175e7ba1
Revises: a2405e0e50ef
Create Date: 2025-06-23 16:02:52.303665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a24175e7ba1'
down_revision: Union[str, Sequence[str], None] = 'a2405e0e50ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitation_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_title', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('topic_number', sa.String(), nullable=True),
    sa.Column('topic_open_date', sa.Date(), nullable=True),
    sa.Column('topic_closed_date', sa.Date(), nullable=True),
    sa.Column('topic_description', sa.String(), nullable=True),
    sa.Column('sbir_topic_link', sa.String(), nullable=True),
    sa.Column('solicitation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solicitation_id'], ['solicitations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitation_topics')
    # ### end Alembic commands ###
