"""initial schema

Revision ID: a2405e0e50ef
Revises: 
Create Date: 2025-06-23 15:20:05.189631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2405e0e50ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitation_id', sa.Integer(), nullable=False),
    sa.Column('solicitation_title', sa.String(), nullable=True),
    sa.Column('solicitation_number', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('solicitation_year', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('application_due_date', sa.String(), nullable=True),
    sa.Column('occurrence_number', sa.Integer(), nullable=True),
    sa.Column('solicitation_agency_url', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitations')
    # ### end Alembic commands ###
